# Generated by Django 2.1.7 on 2019-03-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebs', '0002_auto_20190310_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celeb',
            name='sex',
            field=models.CharField(max_length=1),
        ),
    ]
