# Generated by Django 2.1.7 on 2019-03-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celebs', '0003_auto_20190314_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celeb',
            name='sex',
            field=models.CharField(max_length=6),
        ),
    ]
