# Generated by Django 2.1.5 on 2019-03-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('celebs', '0001_initial'),
        ('movies', '0005_auto_20190310_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('Celeb', 'Celeb'), ('Movie', 'Movie')], max_length=5)),
                ('celebs', models.ManyToManyField(to='celebs.Celeb')),
                ('movies', models.ManyToManyField(to='movies.Movie')),
            ],
        ),
    ]
