# Generated by Django 2.1.5 on 2019-03-10 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='award',
            unique_together={('name', 'kind')},
        ),
    ]
