# Generated by Django 2.1.5 on 2019-03-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_auto_20190310_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
