# Generated by Django 2.1.5 on 2019-03-10 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_actors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='actors',
            new_name='celebs',
        ),
    ]
