# Generated by Django 2.1.5 on 2019-03-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190310_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='celebs',
            field=models.ManyToManyField(blank=True, to='celebs.Celeb'),
        ),
    ]
