# Generated by Django 2.1.5 on 2019-03-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20190310_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
