# Generated by Django 2.1.5 on 2019-03-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20190310_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='logo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
